# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2191a6c736ba1637dc1800e96e863eecb8282a93be9b6b866d2fc2d86c5b90ca8dd0313596633f6af23f32a87467b37255e13d2c5fac5c98da9495030c0aef

test:
  secret_key_base: 2b3e6cd220b70d60c9fbaf56d12407124f3a3d3cf0403ded70d211bf1b184ecbb2cbae5e7c4899438c878eee7a9b2011ef7c262b129376e715312247ed2777ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
